<?php

/**
 * @file
 * Os2dagsorden_settings.
 *
 * PHP version 5
 *
 * @category OS2dagsorden
 * @package OS2dagsorden_Importer
 *  Code for the OS2dagsorden settings feature.
 * @author Stanislav Kutasevits <stan@bellcom.dk>
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
 * @link http://bellcom.dk
 */

include_once 'os2dagsorden_settings.features.inc';

/**
 * Implements hook_menu().
 */
function os2dagsorden_settings_menu() {
  $items['admin/config/os2dagsorden'] = array(
    'title' => 'OS2dagsorden Setup',
    'description' => 'Set up OS2 cms services',
    'position' => 'right',
    'weight' => -15,
    'access callback' => 'os2dagsorden_access_helper_user_has_role',
    'access arguments' => array('administrator+', 'administrator++'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/os2dagsorden/settings'] = array(
    'title' => 'OS2dagsorden Settings',
    'description' => 'General settings for the OS2dagsorden project',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2dagsorden_settings_settings_form'),
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'os2dagsorden_settings.admin.inc',
  );
  $items['admin/config/os2dagsorden/theme_settings'] = array(
    'title' => 'Design changes and colors',
    'description' => 'Design changes and colors',
    'page arguments' => array('os2dagsorden_settings_theme_settings'),
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'os2dagsorden_settings.admin.inc',
  );

  $items['admin/config/os2dagsorden/flush_calendar_preferences'] = array(
    'title' => 'Calendar preferences flushing',
    'description' => 'Clicking on this link all the calendar preferences (pol/org) will be flushed. The preferences are retrieved again from SOFD, once "Importer cron" is run',
    'page callback' => 'os2dagsorden_settings_flush_calendar_preferences',
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['get_committee/autocomplete'] = array(
    'page callback' => 'os2dagsorden_settings_committee_autocomplete_callback',
    'page arguments' => array(2),
    'access arguments' => array('use autocomplete'),
    'type' => MENU_CALLBACK,
  );

  $items['os2dagsorden/export_settings'] = array(
    'page callback' => 'os2dagsorden_settings_export_to_file',
    'access arguments' => array('administer os2web'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Exports all settings to a single file.
 *
 * Useful when settings need to be copied to another installation.
 */
function os2dagsorden_settings_export_to_file() {
  header("Content-type: text/plain");
  header("Content-Disposition:attachment;filename=os2dagsorden_settings.settings");
  ob_clean();

  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_meeting_unpublish_button'] = variable_get('os2dagsorden_show_meeting_unpublish_button', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_import_form_button'] = variable_get('os2dagsorden_show_import_form_button', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_meeting_committee'] = variable_get('os2dagsorden_show_meeting_committee', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_meeting_enddate'] = variable_get('os2dagsorden_show_meeting_enddate', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_meeting_type'] = variable_get('os2dagsorden_show_meeting_type', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_participants_afbud'] = variable_get('os2dagsorden_show_participants_afbud', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_print_icon'] = variable_get('os2dagsorden_show_print_icon', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_send_to_friend_icon'] = variable_get('os2dagsorden_show_send_to_friend_icon', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_generate_pdf_link'] = variable_get('os2dagsorden_show_generate_pdf_link', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_generate_pdf_link_full'] = variable_get('os2dagsorden_show_generate_pdf_link_full', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_bullet_case_id_link'] = variable_get('os2dagsorden_show_bullet_case_id_link', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_bullet_case_id_link_url'] = variable_get('os2dagsorden_bullet_case_id_link_url', "");
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_comments'] = variable_get('os2dagsorden_show_comments', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_closed_bullet_point_content'] = variable_get('os2dagsorden_show_closed_bullet_point_content', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_open_closed_bullet_in_new_tab'] = variable_set('os2dagsorden_open_closed_bullet_in_new_tab', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_bilag'] = variable_get('os2dagsorden_show_bilag', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_sager_group_title'] = variable_get('os2dagsorden_sager_group_title', 'Sager');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_use_abbr'] = variable_get('os2dagsorden_use_abbr', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_bp_comname'] = variable_get('os2dagsorden_show_bp_comname', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_pdf_download_whitelist_enabled'] = variable_get('os2dagsorden_pdf_download_whitelist_enabled', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_pdf_download_whitelist'] = variable_get('os2dagsorden_pdf_download_whitelist', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_sager_group_title'] = variable_get('os2dagsorden_sager_group_title', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_group_closed_bullet_points'] = variable_get('os2dagsorden_group_closed_bullet_points', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_hidden_agenda_committee'] = variable_get('os2dagsorden_hidden_agenda_committee', OS2DAGSORDEN_HIDDEN_AGENGA_COMMITTEE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_download_dropdown'] = variable_get('os2dagsorden_meeting_description_download_dropdown', 'Hent dokumenter');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_download_title'] = variable_get('os2dagsorden_meeting_description_download_title', 'Hent samlet dokument i PDF');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_download_title_additional'] = variable_get('os2dagsorden_meeting_description_download_title_additional', 'Hent tillægsdokument i PDF');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_with_att_download_title'] = variable_get('os2dagsorden_meeting_description_with_att_download_title', 'Samlet dokument med bilag');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_with_att_download_title_additional'] = variable_get('os2dagsorden_meeting_description_with_att_download_title_additional', 'Tillægsdokument med bilag');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_generate_pdf_title'] = variable_get('os2dagsorden_meeting_description_download_title_additional', 'Samlet dokument i PDF');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_generate_pdf_full_title'] = variable_get('os2dagsorden_meeting_description_download_title_additional', 'Samlet dokument med bilag i PDF');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_create_note_text'] = variable_get('os2dagsorden_create_note_text', 'Lav note');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_create_note_hide_text'] = variable_get('os2dagsorden_create_note_hide_text', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_search_switch_to_note_text'] = variable_get('os2dagsorden_search_switch_to_note_text', 'Skift til noter');
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_create_note_text_use_title'] = variable_get('os2dagsorden_create_note_text_use_title', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_bilag_pages_amount'] = variable_get('os2dagsorden_show_bilag_pages_amount', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_group_pager_on_bpa_page'] = variable_get('os2dagsorden_show_group_pager_on_bpa_page', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_notes_page_standart_layout'] = variable_get('os2dagsorden_notes_page_standart_layout', TRUE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_search_restrict_search_function'] = variable_get('os2dagsorden_search_restrict_search_function', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['print_pdf_page_orientation'] = variable_get('print_pdf_page_orientation', PRINT_PDF_PAGE_ORIENTATION_DEFAULT);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_print_pdf_show_commitee'] = variable_get('os2dagsorden_print_pdf_show_commitee', FALSE);
  $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_view_settings_not_attach_addtional_agenda'] = variable_get('os2dagsorden_meeting_view_settings_not_attach_addtional_agenda', FALSE);


  $setting_array['os2dagsorden_speaker_paper_settings']['os2dagsorden_shared_speaker_paper'] = variable_get('os2dagsorden_shared_speaker_paper', TRUE);
  $settings_array['os2dagsorden_speaker_paper_settings']['os2dagsorden_pdf_download_enabled_both_closed_open_agendas_links'] = variable_get('oos2dagsorden_pdf_download_enabled_both_closed_open_agendas_links', FALSE);

  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_hide_meeting_details'] = variable_get('os2dagsorden_hide_meeting_details', FALSE);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_all_bullets'] = variable_get('os2dagsorden_expand_all_bullets', FALSE);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_attachment_onload'] = variable_get('os2dagsorden_expand_attachment_onload', FALSE);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_bilags'] = variable_get('os2dagsorden_expand_bilags', 'true');
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_cases'] = variable_get('os2dagsorden_expand_cases', 'false');
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_massive_expand_collapse_button'] = variable_get('os2dagsorden_show_massive_expand_collapse_button', 'true');
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_bilag_bullet_point'] = variable_get('os2dagsorden_show_bilag_bullet_point', FALSE);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_case_bullet_point'] = variable_get('os2dagsorden_show_case_bullet_point', FALSE);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_bullet_case_nr'] = variable_get('os2dagsorden_show_bullet_case_nr', FALSE);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_attachments_pages_per_view_desktop'] = variable_get('os2dagsorden_attachments_pages_per_view_desktop', 5);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_attachments_pages_per_view_mobile'] = variable_get('os2dagsorden_attachments_pages_per_view_mobile', 3);
  $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_expand_all_button'] = variable_get('os2dagsorden_show_expand_all_button', FALSE);

  $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_latest_meetings_view_mode'] = variable_get('os2dagsorden_latest_meetings_view_mode', 'all');
  $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_show_meeting_title'] = variable_get('os2dagsorden_meetings_views_last_8_show_meeting_title', TRUE);
  $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_show_meeting_committee'] = variable_get('os2dagsorden_meetings_views_last_8_show_meeting_committee', TRUE);
  $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_show_meeting_location'] = variable_get('os2dagsorden_meetings_views_last_8_show_meeting_location', TRUE);
  $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_show_meeting_is_closed'] = variable_get('os2dagsorden_meetings_views_last_8_show_meeting_is_closed', FALSE);
  $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_meeting_title_len'] = variable_get('os2dagsorden_meetings_views_last_8_meeting_title_len', 25);
  $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_meeting_location_len'] = variable_get('os2dagsorden_meetings_views_last_8_meeting_location_len', 25);

  $setting_array['os2dagsorden_frontpage_layout']['os2dagsorden_collapse_menu'] = variable_get('os2dagsorden_collapse_menu', TRUE);
  $setting_array['os2dagsorden_frontpage_layout']['os2dagsorden_collapse_menu_touch'] = variable_get('os2dagsorden_collapse_menu_touch', TRUE);
  $setting_array['os2dagsorden_frontpage_layout']['os2dagsorden_collapse_menu_touch_pages'] = variable_get('os2dagsorden_collapse_menu_touch_pages', 'meetings/print');
  $setting_array['os2dagsorden_frontpage_layout']['os2dagsorden_show_search_block_title'] = variable_get('os2dagsorden_show_search_block_title', 'true');
  $setting_array['os2dagsorden_frontpage_layout']['os2dagsorden_frontpage_layout_show_hide_zoom_buttons'] = variable_get('  os2dagsorden_frontpage_layout_show_hide_zoom_buttons', FALSE);

  $setting_array['os2dagsorden_body_text_layout']['os2dagsorden_body_text_size'] = variable_get('os2dagsorden_body_text_size', '13');
  $setting_array['os2dagsorden_title_text_layout']['os2dagsorden_title_text_size'] = variable_get('os2dagsorden_title_text_size', '13');
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_meetings_search_show_meeting_committee'] = variable_get('os2dagsorden_meetings_search_show_meeting_committee', TRUE);
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_meetings_search_show_meeting_location'] = variable_get('os2dagsorden_meetings_search_show_meeting_location', FALSE);
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_meetings_search_show_meeting_status'] = variable_get('os2dagsorden_meetings_search_show_meeting_status', FALSE);
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_meetings_search_include_add_agenda'] = variable_get('os2dagsorden_meetings_search_include_add_agenda', TRUE);
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_search_startdate'] = variable_get('os2dagsorden_search_startdate', 1);
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_search_enddate'] = variable_get('os2dagsorden_search_enddate', 1);
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_search_meeting_is_closed'] = variable_get('os2dagsorden_search_meeting_is_closed', FALSE);
  $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_meetings_overview_remember_filter_period'] = variable_get('os2dagsorden_meetings_overview_remember_filter_period', 60);

  $setting_array['os2dagsorden_sidepane_menu_layout']['os2dagsorden_budget_committee'] = variable_get('os2dagsorden_budget_committee', FALSE);
  $setting_array['os2dagsorden_sidepane_menu_layout']['os2dagsorden_budgetforhandling_button_committees'] = variable_get('os2dagsorden_budgetforhandling_button_committees', FALSE);

  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_participants_delimeter'] = variable_get('os2dagsorden_participants_delimeter', ', ');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_notification_committee'] = variable_get('os2dagsorden_send_notification_committee', FALSE);
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_email_subject'] = variable_get('os2dagsorden_send_email_subject', '!meeting_type til !committee er publiceret');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_email_body'] = variable_get('os2dagsorden_send_email_body', 'Til !user' . PHP_EOL . PHP_EOL .
      'Du abonnerer på !committee.' . PHP_EOL . 'Der er publiceret !meeting_type til !meeting_name !meeting_date.');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_follows_committee_send_notification'] = variable_get('os2dagsorden_follows_committee_send_notification', FALSE);
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_timespan_of_notification'] = variable_get('os2dagsorden_send_timespan_of_notification', 10);
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_add_type_prefix'] = variable_get('os2dagsorden_add_type_prefix', 'true');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_clean_image_tags'] = variable_get('os2dagsorden_clean_image_tags', TRUE);
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_filtered_tags'] = variable_get('os2dagsorden_filtered_tags', '');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_stripped_tags'] = variable_get('os2dagsorden_stripped_tags', '');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_allowed_span_styles'] = variable_get('os2dagsorden_allowed_span_styles', '');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_tab_tag'] = variable_get('os2dagsorden_tab_tag', '&nbsp;');
  $setting_array['os2dagsorden_meeting_import']['os2dagsorden_url_strip_count'] = variable_get('os2dagsorden_url_strip_count', '20');

  $setting_array['os2dagsorden_meeting_unpublished_state']['os2dagsorden_meeting_unpublished_state_subject'] = variable_get('os2dagsorden_meeting_unpublished_state_subject', '');
  $setting_array['os2dagsorden_meeting_unpublished_state']['os2dagsorden_meeting_unpublished_state_body'] = variable_get('os2dagsorden_meeting_unpublished_state_body', '');

  if (module_exists('os2web_pdf_conversion_manager')) {
    $setting_array['os2dagsorden_file_import']['os2web_copied_filetype'] = variable_get('os2web_copied_filetype', OS2WEB_PDF_CONVERSION_MANAGER_COPIED_FILETYPE);
    $setting_array['os2dagsorden_file_import']['os2web_convertion_dir'] = variable_get('os2web_convertion_dir', OS2WEB_PDF_CONVERSION_MANAGER_CONVERSION_DIR);
  }

  if (module_exists('os2dagsorden_pdf2htmlex')) {
    $setting_array['os2dagsorden_pdf2htmlex_settings']['os2dagsorden_pdf2htmlex_path'] = variable_get('os2dagsorden_pdf2htmlex_path', "");
    $setting_array['os2dagsorden_pdf2htmlex_settings']['pdf2html_rendering_path'] = variable_get('pdf2html_rendering_path', '');
  }

  if (module_exists('os2dagsorden_gs_conversion')) {
    $setting_array['os2dagsorden_gs_conversion_settings']['os2dagsorden_gs_conversion_gs_path'] = variable_get('os2dagsorden_gs_conversion_gs_path', "");
  }
   if (module_exists('os2dagsorden_pdf2png_conversion')) {
    $setting_array['os2dagsorden_pdf2png_conversion_settings']['os2dagsorden_pdf2png_conversion_sedja_console_path'] = variable_get('os2dagsorden_pdf2png_conversion_sedja_console_pathos2dagsorden_clear_cache_active', "");
  }

  $setting_array['os2dagsorden_clear_cache_after_import']['os2dagsorden_clear_cache_active'] = variable_get('os2dagsorden_clear_cache_active', 0);
  $setting_array['os2dagsorden_clear_cache_after_import']['os2dagsorden_clear_cache_frequency'] = variable_get('os2dagsorden_clear_cache_frequency', 0);

  $setting_array['os2dagsorden_committee_category_settings']['os2dagsorden_show_meeting_category'] = variable_get('os2dagsorden_show_meeting_category');
  $setting_array['os2dagsorden_committee_category_settings']['os2dagsorden_user_default_committee_category'] = variable_get('os2dagsorden_user_default_committee_category');
  $setting_array['os2dagsorden_committee_category_settings']['os2dagsorden_committee_forbidden_allowed_categories_mode'] = variable_get('os2dagsorden_committee_forbidden_allowed_categories_mode', 'forbidden');
  $setting_array['os2dagsorden_committee_category_settings']['os2dagsorden_committee_default_forbidden_cat'] = variable_get('os2dagsorden_committee_default_forbidden_cat');

  if (module_exists('os2dagsorden_importer')) {
    $setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_use_local_copy'] = variable_get('os2dagsorden_pws_use_local_copy');
    $setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_v_meetings_url'] = variable_get('os2dagsorden_pws_v_meetings_url');
    $setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_v_meetinggroups_url'] = variable_get('os2dagsorden_pws_v_meetinggroups_url');
    $setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_v_acadregroups_url'] = variable_get('os2dagsorden_pws_v_acadregroups_url');
  }

  if (module_exists('os2dagsorden_acadre_service_importer')) {
    $setting_array['os2dagsorden_acadre_service_importer_placeholder']['os2dagsorden_acadre_service_meetings_url'] = variable_get('os2dagsorden_acadre_service_meetings_url');
    $setting_array['os2dagsorden_acadre_service_importer_placeholder']['os2dagsorden_acadre_service_committees_url'] = variable_get('os2dagsorden_acadre_service_committees_url');
  }

  // The text below are not translatable because those values are already
  // changeable by the settings in os2dagsorden_settings.admin.inc.
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_upcoming_meetings_help_text'] = variable_get('os2dagsorden_upcoming_meetings_help_text', 'Her vises de kommende 5 møder i "Mine udvalg". Det vil sige udvalg som man enten er medlem af eller følger. Udvalgene kan ses i boksene "Medlem af" og "Jeg følger" i højremenuen. Der er ikke en dagsorden tilgængelig før status er angivet til Dagsorden eller Dagsorden+.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_meetings_search_help_text'] = variable_get('os2dagsorden_meetings_search_help_text', 'Her vises de møder der indeholdt møder, punkter eller bilag der matchede dine søgekriterier. Søgeresultatet vises på mødeniveau i listen.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_meetings_search_block_help_text'] = variable_get('os2dagsorden_meetings_search_block_help_text', 'Her kan der søges i dagsordenspunkters tekst og i bilagenes fritekst, hvis sidstnævnte er konverteret til html. Søgning kan filtreres via dato, udvalg og søgeord.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_last_8_meetings_help_text'] = variable_get('os2dagsorden_last_8_meetings_help_text', 'Her vises de seneste 8 møder i alle mødefora. Der er ikke et referat tilgængeligt før status er angivet til Referat eller Referat+.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_annotator_help_text'] = variable_get('os2dagsorden_annotator_help_text', 'Hvis du ønsker at lave en kommentar til et ord eller et afsnit, så marker blot dette hvorefter du får mulighed for at indtaste kommentaren.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_calendar_help_text'] = variable_get('os2dagsorden_calendar_help_text', 'Her findes en dags- eller månedskalender med links til dagsordner og referater hvis de er publicerede. Det er muligt at eksportere møderne til en fil, som så kan importeres til egen kalender, eks. i Outlook.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_user_committees_help_text'] = variable_get('os2dagsorden_user_committees_help_text', 'Her kan du se de udvalg du er medlem af. Ret henvendelse til Direktionssekretariatet hvis du mener det skal ændres.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_user_follows_help_text'] = variable_get('os2dagsorden_user_follows_help_text', 'Her kan du se de udvalg du er sat op til at følge. Følger betyder at du kun kan se åbne punkter og Følger+ betyder at du også kan se lukkede punkter. Ret henvendelse til Direktionssekretariatet hvis du mener det skal ændres.');
  $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_calendar_replacement_block_text'] = variable_get('os2dagsorden_calendar_replacement_block_text', 'Vend venligst din iPad horisontalt');

  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_mine_idstillinger'] = variable_get('os2dagsorden_title_general_mine_idstillinger', 'Mine indstillinger');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_log_off'] = variable_get('os2dagsorden_title_general_log_off', 'Log af');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_search'] = variable_get('os2dagsorden_title_general_search', 'Søg');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_prev_page'] = variable_get('os2dagsorden_title_general_prev_page', 'Forrige');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_next_page'] = variable_get('os2dagsorden_title_general_next_page', 'Næste');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_hide_logout_message'] = variable_get('os2dagsorden_title_general_hide_logout_message', false);

  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_coming_meetings'] = variable_get('os2dagsorden_title_frontpage_coming_meetings', 'Kommende møder i mine udvalg');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_last_8_my_meetings'] = variable_get('os2dagsorden_title_frontpage_last_8_my_meetings', 'Seneste 8 møder i mine udvalg');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_last_8_all_meetings'] = variable_get('os2dagsorden_title_frontpage_last_8_all_meetings', 'Seneste 8 møder i alle udvalg');

  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_calendar'] = variable_get('os2dagsorden_title_frontpage_calendar', 'Kalender');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_member_of'] = variable_get('os2dagsorden_title_frontpage_member_of', 'Medlem af');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_following'] = variable_get('os2dagsorden_title_frontpage_following', 'Jeg følger');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_account_settings'] = variable_get('os2dagsorden_title_frontpage_account_settings', 'Konto indstillinger');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_home'] = variable_get('os2dagsorden_title_frontpage_home', 'Forsiden');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_halfyear_calendar'] = variable_get('os2dagsorden_title_frontpage_halfyear_calendar', 'Halvårs-kalender');

  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_status'] = variable_get('os2dagsorden_title_meeting_status', 'Status');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_meeting'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_date'] = variable_get('os2dagsorden_title_meeting_date', 'Dato');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_location'] = variable_get('os2dagsorden_title_meeting_location', 'Lokation');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_freetext_placing'] = variable_get('os2dagsorden_title_meeting_freetext_placing', 'Placering');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_comments'] = variable_get('os2dagsorden_title_meeting_comments', 'Bemærkninger');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_special_comments'] = variable_get('os2dagsorden_title_meeting_special_comments', 'Særlige forhold');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_participants'] = variable_get('os2dagsorden_title_meeting_participants', 'Deltagere');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_cancelled_participants'] = variable_get('os2dagsorden_title_meeting_cancelled_participants', 'Afbud / Fraværende');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_referent'] = variable_get('os2dagsorden_title_meeting_referent', 'Referent');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_agenda'] = variable_get('os2dagsorden_title_meeting_agenda', 'Dagsorden:');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_closed_agenda'] = variable_get('os2dagsorden_title_meeting_closed_agenda', 'Lukket Dagsorden:');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_committee'] = variable_get('os2dagsorden_title_meeting_committee', 'Udvalg');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_see_all_speakerpapers'] = variable_get('os2dagsorden_title_meeting_see_all_speakerpapers', 'Se alle talepapirer');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_print_all_speakerpapers'] = variable_get('os2dagsorden_title_meeting_print_all_speakerpapers', 'Print alle talepapirer');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_meeting_notes_title'] = variable_get('os2dagsorden_meeting_notes_title', 'Mødernoter');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_new_speaker_paper'] = variable_get('os2dagsorden_title_meeting_new_speaker_paper', 'Nyt talepapir');
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_new_speaker_paper_hide'] = variable_get('os2dagsorden_title_meeting_new_speaker_paper_hide', FALSE);
  $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_create_meeting'] = variable_get('os2dagsorden_title_general_create_meeting', 'Tilføj møde');

  $setting_array['os2dagsorden_meeting_view_calendar_settings']['os2dagsorden_meeting_view_calendar_short_name'] = variable_get('os2dagsorden_meeting_view_calendar_short_name');
  $setting_array['os2dagsorden_meeting_view_calendar_settings']['os2dagsorden_meeting_show_calendar_block_on_cal_pages'] = variable_get('os2dagsorden_meeting_show_calendar_block_on_cal_pages');

  $setting_array['os2dagsorden_token_login_settings']['os2dagsorden_token_login_ip_whitelist'] = variable_get('os2dagsorden_token_login_ip_whitelist');
  $setting_array['os2dagsorden_token_login_settings']['os2dagsorden_token_login_allowed_paths'] = variable_get('os2dagsorden_token_login_allowed_paths', '<front>');

  $setting_array['os2dagsorden_external_committee']['os2dagsorden_external_committee_anonymize_button_behavior'] = variable_get('os2dagsorden_external_committee_anonymize_button_behavior', 'anonymize');
  $setting_array['os2dagsorden_external_committee']['os2dagsorden_timespan_open_meeting_content'] = variable_get('os2dagsorden_timespan_open_meeting_content', 'anonymize');

  $setting_array['os2dagsorden_right_sidebar_arrow_position']['os2dagsorden_right_sidebar_arrow_position_radios'] = variable_get('os2dagsorden_right_sidebar_arrow_position_radios', 'classic');

  if (module_exists('os2dagsorden_automated_logout_configuration')) {
    $setting_array['os2dagsorden_automated_logout_configuration_settings']['os2dagsorden_automated_logout_show_autologout_inactivity_message'] =  variable_get('os2dagsorden_automated_logout_show_autologout_inactivity_message', TRUE);
  }
  $setting_array['upload_guide']['quick_guide_upload_fid'] = variable_get('quick_guide_upload_fid');
  print os2dagsorden_settings_write_ini_file($setting_array, TRUE);
}

/**
 * Flushed the preferences of all the users regarding the calendar (pol/org)
 */
function os2dagsorden_settings_flush_calendar_preferences() {
  $users = db_select('users', 'u')
    ->fields('u', array('uid'))
    ->execute()
    ->fetchAll();
  foreach ($users as $user) {
    if ($user->uid === 0) {
      continue;
    }

    $user = user_load($user->uid);
    $user->field_user_com_categ['und'] = array();
    user_save($user);
  }

  drupal_set_message('All users calendar preferences have been flushed');
  drupal_goto('admin/config');
}

/**
 * Helper function for committee autocomplete.
 *
 * @param string $string
 *   Search string.
 */
function os2dagsorden_settings_committee_autocomplete_callback($string = '') {
  $vid = db_select('taxonomy_vocabulary', 'tv')
    ->fields('tv', array('vid'))
    ->condition('machine_name', 'os2web_meetings_tax_committee')
    ->execute()
    ->fetchField();
  $vocabulary_terms = taxonomy_get_tree($vid);
  $array = drupal_explode_tags($string);
  $last_string = trim(array_pop($array));
  $matches = array();
  $prefix = count($array) ? implode(', ', $array) . ', ' : '';
  foreach ($vocabulary_terms as $term) {
    $terms[$prefix . $term->name] = $term->name;
  }
  drupal_json_output($terms);
}

/**
 * Implements hook_views_pre_render().
 *
 * Alters the view title (block titles) - by using the values from the settings.
 */
function os2dagsorden_settings_views_pre_render(&$view) {
  if ($view->name === 'user_committee') {
    $view->build_info['title'] = variable_get('os2dagsorden_title_frontpage_member_of', 'Medlem af');
  }
  if ($view->name === 'user_follow_committees') {
    $view->build_info['title'] = variable_get('os2dagsorden_title_frontpage_following', 'Jeg følger');
  }
}

/**
 * Implements hook_views_pre_view().
 *
 * Alters various texts - by using the values from the settings.
 */
function os2dagsorden_settings_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name === 'seneste_8_m_der_i_de_st_ende_politiske_udvalg_') {
    $view->display_handler->options['fields']['field_os2web_meetings_type']['label'] = variable_get('os2dagsorden_title_meeting_status', 'Status');
    $view->display_handler->options['fields']['php_2']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    $view->display_handler->options['fields']['field_os2web_meetings_date']['label'] = variable_get('os2dagsorden_title_meeting_date', 'Dato');
    $view->display_handler->options['fields']['php_4']['label'] = variable_get('os2dagsorden_title_meeting_location', 'Lokation');
  }
  elseif ($view->name === 'meetings_search') {
    $view->display_handler->options['fields']['php_7']['label'] = variable_get('os2dagsorden_title_meeting_status', 'Status');
    $view->display_handler->options['fields']['php_2']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    $view->display_handler->options['fields']['php_3']['label'] = variable_get('os2dagsorden_title_meeting_freetext_placing', 'Placering');
    $view->display_handler->options['fields']['field_os2web_meetings_date']['label'] = variable_get('os2dagsorden_title_meeting_date', 'Dato');
  }
  elseif ($view->name === 'kommende_m_der_i_mine_udvalg') {
    // This view has only one display, hence using different logic for setting the label.
    $view->display_handler->default_display->options['fields']['php_2']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    $view->display_handler->default_display->options['fields']['php_4']['label'] = variable_get('os2dagsorden_title_meeting_location', 'Lokation');
  }
  elseif ($view->name === 'meeting_details') {
    if ($view->display_handler->options['fields']['title']['id']) {
      $view->display_handler->options['fields']['title']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    }
    if ($view->display_handler->options['fields']['field_os2web_meetings_location']['id']) {
      $view->display_handler->options['fields']['field_os2web_meetings_location']['label'] = variable_get('os2dagsorden_title_meeting_location', 'Lokation');
    }
    if ($view->display_handler->options['fields']['php_3']['id']) {
      $view->display_handler->options['fields']['php_3']['label'] = variable_get('os2dagsorden_title_meeting_committee', 'Udvalg');
    }
    if ($view->display_handler->options['fields']['field_os2web_meetings_comments']['id']) {
      $view->display_handler->options['fields']['field_os2web_meetings_comments']['label'] = variable_get('os2dagsorden_title_meeting_comments', 'Bemærkninger');
    }
    if ($view->display_handler->options['fields']['field_os2web_meetings_conditions']['id']) {
      $view->display_handler->options['fields']['field_os2web_meetings_conditions']['label'] = variable_get('os2dagsorden_title_meeting_special_comments', 'Særlige forhold');
    }
    if ($view->display_handler->options['fields']['php']['ui_name'] === 'Participants') {
      $view->display_handler->options['fields']['php']['label'] = variable_get('os2dagsorden_title_meeting_participants', 'Deltagere');
    }
    if ($view->display_handler->options['fields']['php']['ui_name'] === 'Participants (Cancelled)') {
      $view->display_handler->options['fields']['php']['label'] = variable_get('os2dagsorden_title_meeting_cancelled_participants', 'Afbud / Fraværende');
    }
  }
  elseif ($view->name === 'os2dagsorden_users_view') {
    $vid = db_select('taxonomy_vocabulary', 'tv')
      ->fields('tv', array('vid'))
      ->condition('machine_name', 'os2web_meetings_tax_committee')
    // ORDER BY created.
      ->orderBy('name', 'ASC')
      ->execute()
      ->fetchField();

    foreach (taxonomy_get_tree($vid, 0, 1) as $com) {
      $first_level_committees[$com->name] = $com->tid;
    }
    ksort($first_level_committees);

    foreach ($first_level_committees as $com) {
      $view->display_handler->default_display->options['filters']['field_user_committee_tid']['value'][$com] = $com;
      $view->display_handler->default_display->options['filters']['field_follows_committee_tid']['value'][$com] = $com;
      $view->display_handler->default_display->options['filters']['field_follows_committee_plus_tid']['value'][$com] = $com;
      $view->display_handler->default_display->options['filters']['field_follows_committee_pp_tid']['value'][$com] = $com;
    }

    $view->display_handler->default_display->options['filters']['field_user_committee_tid']['expose']['reduce'] = 1;
    $view->display_handler->default_display->options['filters']['field_follows_committee_tid']['expose']['reduce'] = 1;
    $view->display_handler->default_display->options['filters']['field_follows_committee_plus_tid']['expose']['reduce'] = 1;
    $view->display_handler->default_display->options['filters']['field_follows_committee_pp_tid']['expose']['reduce'] = 1;
  }
}

/**
 * Helper function.
 *
 * Which creates ini file based on the provided associative array.
 *
 * @param mixed $assoc_arr
 *   The associative array.
 * @param bool $has_sections
 *   The has_section flag.
 *
 * @return string
 *   The content of INI file.
 */
function os2dagsorden_settings_write_ini_file($assoc_arr, $has_sections = FALSE) {
  $content = "";
  if ($has_sections) {
    foreach ($assoc_arr as $key => $elem) {
      $content .= "[" . $key . "]\n";
      foreach ($elem as $key2 => $elem2) {
        if (is_array($elem2)) {
          foreach ($elem2 as $key3 => $elem3) {
            $content .= $key2 . "[" . $key3 . "] = \"" . $elem3 . "\"\n";
          }
        }
        elseif ($elem2 === "") {
          $content .= $key2 . " = \n";
        }
        else {
          $content .= $key2 . " = \"" . $elem2 . "\"\n";
        }
      }
    }
  }
  else {
    foreach ($assoc_arr as $key => $elem) {
      if (is_array($elem)) {
        for ($i = 0; $i < count($elem); $i++) {
          $content .= $key . "[] = \"" . $elem[$i] . "\"\n";
        }
      }
      elseif ($elem === "") {
        $content .= $key . " = \n";
      }
      else {
        $content .= $key . " = \"" . $elem . "\"\n";
      }
    }
  }

  return $content;
}

/**
 * Implements hook_form_alter().
 *
 * Does various modifications to the custom forms based on the os2dagsorden
 * settings state.
 */
function os2dagsorden_settings_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-meetings-search-page' || $form['#id'] === 'views-exposed-form-meetings-search-page-meetings-overview') {
    if (empty($_GET['from_date'])) {
      $form['from_date']['value']['#default_value'] = date('Y-m-d', strtotime('-' . variable_get('os2dagsorden_search_startdate', 1) . ' months'));
    }
    if (empty($_GET['to_date'])) {
      $form['to_date']['value']['#default_value'] = date('Y-m-d', strtotime('+' . variable_get('os2dagsorden_search_enddate', 1) . ' months'));
    }
    $form['submit']['#value'] = variable_get('os2dagsorden_title_general_search', 'Søg');

    // Limiting to only positive committee list.
    $com_pos_list = array();
    $active_commitees = os2dagsorden_settings_get_active_committees();

    foreach ($active_commitees as $com) {
      $com_pos_list[$com->tid] = $com->name;
    }
    if (!empty($active_commitees)) {
      $form['field_os2web_meetings_committee_tid_depth']['#empty_option'] = array('All' => 'Alle');
      $form['field_os2web_meetings_committee_tid_depth']['#options'] = $com_pos_list;
    }
  }

  if ($form['#id'] === 'views-exposed-form-meetings-search-page-meetings-overview') {
    $form['bpa_filter'] = array(
      '#type' => 'select',
      '#title' => t('Udvalgt punkter:'),
      '#options' => array(
        'resum' => t('Resume'),
        'sagsfremstilling' => t('Sagsfremstilling'),
        'Økonomi og organisatoriske konsekvenser' => t('Økonomi og organisatoriske konsekvenser'),
        'lovgrundlag' => t('Lovgrundlag'),
        'bilag' => t('Bilag'),
        'indstilling' => t('Indstilling'),
        'beslutning' => t('Beslutning'),
        'supplerende sagsfremstilling' => t('Supplerende sagsfremstilling'),
      ),
      '#default_value' => 0,
      '#multiple' => TRUE,
    );
    $submit = $form['submit'];
    unset($form['submit']);
    $form['submit'] = $submit;
  }

  if ($form['#id'] === 'views-exposed-form-os2dagsorden-users-view-system-1') {
    asort($form['field_user_committee_tid']['#options']);
    asort($form['field_follows_committee_tid']['#options']);
    asort($form['field_follows_committee_plus_tid']['#options']);
    asort($form['field_follows_committee_pp_tid']['#options']);
  }

  if ($form_id === 'os2dagsorden_settings_settings_form') {
    $form['#submit'][] = 'os2dagsorden_settings_guide_file_lock';
  }

  if ($form['#id'] === 'system-theme-settings') {
    $form['#submit'][] = 'os2dagsorden_settings_theme_settings_submit';
  }
}

/**
 * Form submit.
 *
 * Function that adds/removes quick guide file from/to file usage table.
 *
 * @param mixed $form
 *   The settings form.
 * @param mixed $form_state
 *   The state of form.
 */
function os2dagsorden_settings_guide_file_lock($form, &$form_state) {
  if (isset($form_state['values']['quick_guide_upload_fid']) && !empty($form_state['values']['quick_guide_upload_fid'])) {
    $fid = $form_state['values']['quick_guide_upload_fid'];
    if (($file = file_load($fid)) && empty($file->status)) {
      $file->status = FILE_STATUS_PERMANENT;
      file_save($file);
      if (!file_lock_is_locked($file)) {
        // Only add one lock for every file.
        file_usage_add($file, 'os2dagsorden_settings', 'module', FILE_LOCK_ID);
      }
    }
  }
  else {
    $result = db_select('file_usage', 'f')
      ->fields('f', array('fid'))
      ->condition('module', 'os2dagsorden_settings')
      ->execute();
    foreach ($result as $files) {
      file_delete(file_load($files->fid), TRUE);
    }
  }
}

/**
 * Implements hook_block_view_alter().
 *
 * Alters various texts - by using the values from the settings.
 */
function os2dagsorden_settings_block_view_alter(&$data, $block) {
  switch ($block->delta) {
    case '-exp-meetings_search-page':
      $data['content']['#markup'] = '<div class="help-button" id="os2dagsorden_meetings_search_block_help" aria-label="' . variable_get('os2dagsorden_meetings_search_block_help_text', 'Her kan der søges i dagsordenspunkters tekst og i bilagenes fritekst, hvis sidstnævnte er konverteret til html. Søgning kan filtreres via dato, udvalg og søgeord.') . '"></div>' . $data['content']['#markup'];
      $block->title = variable_get('os2dagsorden_title_general_search', 'Søg');
      break;

    case 'events-block_1':
      $block->title = variable_get('os2dagsorden_title_frontpage_calendar', 'Kalender');
      break;

    case 'menu-sidepane-menu':
      foreach ($data['content'] as &$menu_item) {
        // Filtering on actual menus.
        if ($menu_item['#theme'] === 'menu_link__menu_sidepane_menu') {
          // Menu title: Forsiden.
          if ($menu_item['#title'] === 'Forsiden') {
            $menu_item['#title'] = variable_get('os2dagsorden_title_frontpage_home', 'Forsiden');
          }
          // Menu title: Halvårs-kalender.
          if ($menu_item['#title'] === 'Halvårs-kalender') {
            $menu_item['#title'] = variable_get('os2dagsorden_title_frontpage_halfyear_calendar', 'Halvårs-kalender');
          }
        }
      }
      break;

    // Block named: Last 8 meeting in all committees/
    // Seneste 8 møder i alle udvalg.
    case 'c8c6c91b397acf23018fcefd40a1fa29':
      $block->title = variable_get('os2dagsorden_title_frontpage_last_8_all_meetings', 'Seneste 8 møder i alle udvalg');
      break;

    // Block named: Last 8 meeting in my committees/
    // Seneste 8 møder i mine udvalg.
    case '0293ca2a3a9d3ff12dd399cf7b0b4333':
      $block->title = variable_get('os2dagsorden_title_frontpage_last_8_my_meetings', 'Seneste 8 møder i mine udvalg');
      break;
  }
}

/**
 * Helper function that returns a list of active committees from the settings.
 *
 * @return mixed
 *   Array of of active committees list.
 */
function os2dagsorden_settings_get_active_committees() {
  $vid = db_select('taxonomy_vocabulary', 'tv')
    ->fields('tv', array('vid'))
    ->condition('machine_name', 'os2web_meetings_tax_committee')
    ->execute()
    ->fetchField();

  $committees = taxonomy_get_tree($vid);

  $active_committees = array();
  foreach ($committees as $committee) {
    $committee_full = taxonomy_term_load($committee->tid);
    if (isset($committee_full->field_os2web_meetings_com_active['und']) && $committee_full->field_os2web_meetings_com_active['und'][0]['value']) {
      $active_committees[$committee_full->tid] = $committee_full;
    }
  }
  uasort($active_committees, 'os2dagsorden_access_helper_compare_term_by_name');
  return $active_committees;
}

/**
 * Helper functions.
 *
 * That returns the subid of the committees that are set to be imported.
 *
 * @return mixed
 *   The subid of the committees that are set to be imported.
 */
function os2dagsorden_settings_get_import_committees_sub_id() {
  $vid = db_select('taxonomy_vocabulary', 'tv')
    ->fields('tv', array('vid'))
    ->condition('machine_name', 'os2web_meetings_tax_committee')
    ->execute()
    ->fetchField();

  $committees = taxonomy_get_tree($vid);

  $ids = array();
  foreach ($committees as $committee) {
    $committee_full = taxonomy_term_load($committee->tid);
    if (isset($committee_full->field_os2web_meetings_com_import['und']) && $committee_full->field_os2web_meetings_com_import['und'][0]['value']) {
      if (isset($committee_full->field_os2web_meetings_com_subid['und'])) {
        foreach ($committee_full->field_os2web_meetings_com_subid['und'] as $id) {
          $ids[] = $id['value'];
        }
      }
    }
  }

  return $ids;
}

/**
 * Function that prints links to quick guide document.
 */
function os2dagsorden_settings_get_quide_link() {
  $fid = variable_get('quick_guide_upload_fid', '');
  if ($fid && is_numeric($fid)) {
    $file = file_load($fid);
    $uri = $file->uri;
    $url = file_create_url($uri);
    print l(t('Vejledning'), $url, array('attributes' => array('class' => 'user-guide-btn button', 'target' => '_blank')));
  }
}

/**
 * Implements custom submit function for theme settings form.
 *
 * @param mixed $form
 *   The form element.
 * @param mixed $form_state
 *   The state of form.
 */
function os2dagsorden_settings_theme_settings_submit($form, &$form_state) {
  if (isset($form_state['values']['logo_upload']) && !empty($form_state['values']['logo_upload'])) {
    $file = $form_state['values']['logo_upload'];
    $dest = 'public://' . $file->filename;
    $new_file = file_copy($file, $dest);
    $theme_settings = variable_get('theme_' . variable_get('theme_default') . '_settings');
    $theme_settings['logo_path'] = $new_file->uri;
    variable_set('theme_' . variable_get('theme_default') . '_settings', $theme_settings);
  }
  if (isset($form_state['values']['favicon_upload']) && !empty($form_state['values']['favicon_upload'])) {
    $file = $form_state['values']['favicon_upload'];
    $dest = 'public://' . $file->filename;
    $new_file = file_copy($file, $dest);
    $theme_settings = variable_get('theme_' . variable_get('theme_default') . '_settings');
    $theme_settings['favicon_path'] = $new_file->uri;
    variable_set('theme_' . variable_get('theme_default') . '_settings', $theme_settings);
  }
}
