<?php

/**
 * @file
 * Code for the Os2web - meetings content types feature.
 */

include_once 'os2web_meetings_content_types.features.inc';

define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_PLANNED', 'Planlagt');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_CHANGED', 'Ændret');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_CANCELLED', 'Aflyst');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_PREMEETING', 'Premeeting');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_PREMEETING_PLUS', 'Premeeting_plus');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_DAGSORDEN', 'Dagsorden');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_DAGSORDEN_PLUS', 'Dagsorden_plus');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_REFERAT', 'Referat');
define('OS2WEB_MEETINGS_CONTENT_TYPES_MEETING_REFERAT_PLUS', 'Referat_plus');
