<?php

/**
 * @file
 * Code for the OS2Web Meeting Views feature.
 */

include_once 'os2dagsorden_meeting_views.features.inc';
include_once 'inc/os2dagsorden_meeting_views_common_fields.inc';

include_once 'inc/os2dagsorden_meeting_views_meeting_details_fields.inc';
include_once 'inc/os2dagsorden_meeting_views_bullet_point_fields.inc';
include_once 'inc/os2dagsorden_meeting_views_meetings_search_fields.inc';
include_once 'inc/os2dagsorden_meeting_views_last_8_meetings_fields.inc';
include_once 'inc/os2dagsorden_meeting_views_coming_meetings_fields.inc';
include_once 'inc/os2dagsorden_meeting_views.pdf_generation.inc';

/**
 * Implements hook_menu().
 */
function os2dagsorden_meeting_views_menu() {
  $items['admin/config/os2dagsorden/meetings-overview'] = array(
    'title' => 'Mødeudtræk',
    'description' => 'Giver en søge oversigt hvor man kan vælge et udvalg of få udtrukket, f.eks. alle beslutnings sektioner pa møderne. Listen kan generes for en periode også',
    'page callback' => 'os2dagsorden_meeting_views_meetings_overview_callback',
    'access callback' => 'os2dagsorden_access_helper_user_has_role',
    'access arguments' => array('administrator+', 'administrator++'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['meetings-overview/pdf'] = array(
    'title' => 'PDF Dagsorden',
    'type' => MENU_CALLBACK,
    'page callback' => 'os2dagsorden_meeting_views_meetings_overview_pdf_generate',
    'access callback' => 'os2dagsorden_access_helper_user_has_role',
    'access arguments' => array('administrator+', 'administrator++'),
  );

  return $items;
}

/**
 * Page callback to send to meetings overview page.
 */
function os2dagsorden_meeting_views_meetings_overview_callback() {
  drupal_goto('meetings-overview');
}

/**
 * Implements hook_form_alter().
 */
function os2dagsorden_meeting_views_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'views_exposed_form' && $form['#id'] === 'views-exposed-form-meetings-search-page-meetings-overview') {
    $form['submit']['#name'] = 'search';

    $form['reset'] = array(
      '#name' => 'reset',
      '#type' => 'submit',
      '#value' => t('Nulstil søgning'),
    );

    $form['#submit'][] = 'os2dagsorden_meeting_views_meetings_overview_submit';
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * Updates pager count.
 */
function os2dagsorden_meeting_views_views_pre_render(&$view) {
  if ($view->name === 'meetings_search' && $view->current_display === 'page_meetings_overview') {
    $count = $view->query->pager->total_items;
    foreach ($view->result as $result_delta => $result) {
      $rendered_meeting = node_view(node_load($result->nid), 'os2dagsorden_meeting_overview');
      if (empty($rendered_meeting['field_os2web_meetings_bullets']['#items'])) {
        unset($view->result[$result_delta]);
        $count--;
      }
    }

    // Reset the count of items.
    $view->query->pager->total_items = $count;
    $view->query->pager->update_page_info();
  }
  if (($view->name === 'meeting_details' || $view->name === 'speaking_paper') && $view->current_display === 'page') {
    $meeting_id = arg(1);
    $view_title = $view->get_title();
    $meeting_title = node_load($meeting_id)->title;
    $view->set_title($meeting_title . ' - ' . $view_title);
  }
}

/**
 * Implements hook_views_pre_build().
 *
 * Resets the exposed filter values.
 */
function os2dagsorden_meeting_views_views_pre_build(&$view) {
  if ($view->name === 'meetings_search' && $view->current_display === 'page_meetings_overview') {
    if (isset($_SESSION['views']['meetings_search']['page_meetings_overview'])) {
      if (isset($_SESSION['views']['meetings_search']['page_meetings_overview']['submit_time'])) {
        $submit_time = $_SESSION['views']['meetings_search']['page_meetings_overview']['submit_time'];

        // Converting allowed period in minutes to seconds.
        $allowed_period_s = variable_get('os2dagsorden_meetings_overview_remember_filter_period', 60) * 60;

        if (time() - $submit_time > $allowed_period_s) {
          unset($_SESSION['views']['meetings_search']['page_meetings_overview']);
          $view->exposed_data = array();
        }
      }
    }
  }
  if ($view->name == 'meeting_details' && variable_get('os2dagsorden_meeting_view_settings_not_attach_addtional_agenda', FALSE)) {
    if (isset($view->display['attachment_8'])) {
      unset($view->display['attachment_8']);
    }
  }
}

/**
 * Updates the submit time and handles reset logic.
 *
 * @param mixed $form
 * @param mixed $form_state
 */
function os2dagsorden_meeting_views_meetings_overview_submit(&$form, &$form_state) {
  if ($form_state['triggering_element']['#name'] === 'search') {
    $_SESSION['views']['meetings_search']['page_meetings_overview']['submit_time'] = time();
  }
  elseif ($form_state['triggering_element']['#name'] === 'reset' && $_GET['reset']) {
    unset($_SESSION['views']['meetings_search']['page_meetings_overview']);

    $form_state['rebuild'] = TRUE;

    // Forcing redirect.
    os2dagsorden_meeting_views_meetings_overview_callback();
  }
}

/**
 * Implements hook_view_node().
 *
 * @param mixed $node
 *   The node that is being assembled for rendering.
 * @param mixed $view_mode
 *   The $view_mode parameter from node_view().
 * @param string $langcode
 *   The language code used for rendering.
 */
function os2dagsorden_meeting_views_node_view($node, $view_mode, $langcode) {
  if ($node->type === 'os2web_meetings_meeting' && $view_mode === 'os2dagsorden_meeting_overview') {
    foreach ($node->content['field_os2web_meetings_bullets'] as $bp_delta => $bp) {
      if (is_array($bp) && isset($bp['node'])) {
        $bp = reset($bp['node']);

        // Does BP have any BPA?
        if (empty($bp['field_os2web_meetings_attach']['#items'])) {
          unset($node->content['field_os2web_meetings_bullets'][$bp_delta]);
          unset($node->content['field_os2web_meetings_bullets']['#items'][$bp_delta]);
        }
      }
    }
  }

  if ($node->type === 'os2web_meetings_bullet' && $view_mode === 'teaser') {
    $bpa_filters = array();
    if (isset($_GET['bpa_filter'])) {
      $bpa_filters = $_GET['bpa_filter'];
    }

    if (isset($node->content['field_os2web_meetings_attach'])) {
      $attachments_unique = array();

      foreach ($node->content['field_os2web_meetings_attach'] as $bpa_delta => $bpa) {
        if (is_array($bpa) && isset($bpa['node'])) {
          $bpa = reset($bpa['node']);
          $bpa_node = $bpa['#node'];

          // Duplicate attachment?
          if (in_array($bpa_node->nid, $attachments_unique)) {
            unset($node->content['field_os2web_meetings_attach'][$bpa_delta]);
            unset($node->content['field_os2web_meetings_attach']['#items'][$bpa_delta]);
          }
          else {
            $attachments_unique[] = $bpa_node->nid;
          }

          // Does BPA have text?
          if (empty($bpa_node->field_os2web_meetings_bpa_body)) {
            unset($node->content['field_os2web_meetings_attach'][$bpa_delta]);
            unset($node->content['field_os2web_meetings_attach']['#items'][$bpa_delta]);
          }
          elseif (!empty($bpa_filters)) {
            // Does BPA match search criteria?
            $to_unset = TRUE;
            foreach ($bpa_filters as $bpa_filter) {
              if (strncasecmp($bpa_filter, $bpa_node->title, strlen($bpa_filter)) === 0) {
                $to_unset = FALSE;
              }
            }
            if ($to_unset) {
              unset($node->content['field_os2web_meetings_attach'][$bpa_delta]);
              unset($node->content['field_os2web_meetings_attach']['#items'][$bpa_delta]);
            }
          }
        }
      }
    }
  }
}
