<?php

/**
 * @file
 * Os2dagsorden_acadre_service_importer.
 *
 * PHP version 5
 *
 * @category OS2Dagsorden
 * @package Os2dagsorden_acadre_service_importer
 *  Install file
 * @author Stanislav Kutasevits <stan@bellcom.dk>
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
 * @link http://bellcom.dk
 */

/**
 * Implements hook_requirements().
 */
function os2dagsorden_acadre_service_importer_requirements($phase) {
  if ($phase !== 'runtime') {
    return array();
  }
  $t = get_t();

  if (!empty(variable_get('os2dagsorden_acadre_service_meetings _url', ''))) {
    $requirements['os2dagsorden_acadre_service_importer_meetings_url'] = array(
      'title' => $t('OS2Dagsorden meetings importer webservice.'),
    );
    if (!_os2dagsorden_acadre_service_importer_webservice_url_exists(variable_get('os2dagsorden_acadre_service_meetings_url'))) {
      $requirements['os2dagsorden_acadre_service_importer_meetings_url']['value'] = $t('Not accessible');
      $requirements['os2dagsorden_acadre_service_importer_meetings_url']['severity'] = REQUIREMENT_ERROR;
      $requirements['os2dagsorden_acadre_service_importer_meetings_url']['description'] = t('Webservice %variable  is not accessible', array('%variable' => variable_get('os2dagsorden_acadre_service_meetings_url')));
    }
    else {
      $requirements['os2dagsorden_acadre_service_importer_meetings_url']['value'] = $t('Webservice accessible');
      $requirements['os2dagsorden_acadre_service_importer_meetings_url']['severity'] = REQUIREMENT_OK;
      $requirements['os2dagsorden_acadre_service_importer_meetings_url']['description'] = t('Webservice %variable  is accessible', array('%variable' => variable_get('os2dagsorden_acadre_service_meetings_url')));
    }
  }
  if (!empty(variable_get('os2dagsorden_acadre_service_committees_url'))) {
    $requirements['os2dagsorden_acadre_service_importer_committees_url'] = array(
      'title' => $t('OS2Dagsorden committees importer webservice.'),
    );
    if (!_os2dagsorden_acadre_service_importer_webservice_url_exists(variable_get('os2dagsorden_acadre_service_committees_url'))) {
      $requirements['os2dagsorden_acadre_service_importer_committees_url']['value'] = $t('Not accessible');
      $requirements['os2dagsorden_acadre_service_importer_committees_url']['severity'] = REQUIREMENT_ERROR;
      $requirements['os2dagsorden_acadre_service_importer_committees_url']['description'] = t('Webservice %variable  is not accessible', array('%variable' => variable_get('os2dagsorden_acadre_service_committees_url')));
    }
    else {
      $requirements['os2dagsorden_acadre_service_importer_committees_url']['value'] = $t('Webservice accessible');
      $requirements['os2dagsorden_acadre_service_importer_committees_url']['severity'] = REQUIREMENT_OK;
      $requirements['os2dagsorden_acadre_service_importer_committees_url']['description'] = t('Webservice %variable  is accessible', array('%variable' => variable_get('os2dagsorden_acadre_service_committees_url')));
    }
  }
  return $requirements;
}
