<?php

/**
 * @file
 * Installation file for Os2dagsorden importer module.
 */

/**
 * Implements hook_requirements().
 */
function os2dagsorden_importer_requirements($phase) {
  if ($phase !== 'runtime') {
    return array();
  }
  $t = get_t();
  if (!variable_get('os2dagsorden_pws_use_local_copy')) {

    $requirements['os2dagsorden_importer_meetings_url'] = array(
      'title' => $t('OS2Dagsorden importer webservice.'),
    );
    if (!_os2dagsorden_importer_webservice_url_exists(variable_get('os2dagsorden_pws_v_meetings_url'))) {
      $requirements['os2dagsorden_importer_meetings_url']['value'] = $t('Not accessible');
      $requirements['os2dagsorden_importer_meetings_url']['severity'] = REQUIREMENT_ERROR;
      $requirements['os2dagsorden_importer_meetings_url']['description'] = t('Webservice %variable  is not accessible', array('%variable' => variable_get('os2dagsorden_pws_v_meetings_url')));
    }
    else {
      $requirements['os2dagsorden_importer_meetings_url']['value'] = $t('Webservice accessible');
      $requirements['os2dagsorden_importer_meetings_url']['severity'] = REQUIREMENT_OK;
      $requirements['os2dagsorden_importer_meetings_url']['description'] = t('Webservice %variable  is accessible', array('%variable' => variable_get('os2dagsorden_pws_v_meetings_url')));
    }

    $requirements['os2dagsorden_importer_meetinggroups_url'] = array(
      'title' => $t('OS2Dagsorden importer webservice.'),
    );
    if (!_os2dagsorden_importer_webservice_url_exists(variable_get('os2dagsorden_pws_v_meetinggroups_url'))) {
      $requirements['os2dagsorden_importer_meetinggroups_url']['value'] = $t('Not accessible');
      $requirements['os2dagsorden_importer_meetinggroups_url']['severity'] = REQUIREMENT_ERROR;
      $requirements['os2dagsorden_importer_meetinggroups_url']['description'] = t('Webservice %variable  is not accessible', array('%variable' => variable_get('os2dagsorden_pws_v_meetinggroups_url')));
    }
    else {
      $requirements['os2dagsorden_importer_meetinggroups_url']['value'] = $t('Webservice accessible');
      $requirements['os2dagsorden_importer_meetinggroups_url']['severity'] = REQUIREMENT_OK;
      $requirements['os2dagsorden_importer_meetinggroups_url']['description'] = t('Webservice %variable  is accessible', array('%variable' => variable_get('os2dagsorden_pws_v_meetinggroups_url')));
    }

    $requirements['os2dagsorden_importer_acadregroups_url'] = array(
      'title' => $t('OS2Dagsorden importer webservice.'),
    );
    if (!_os2dagsorden_importer_webservice_url_exists(variable_get('os2dagsorden_pws_v_acadregroups_url'))) {
      $requirements['os2dagsorden_importer_acadregroups_url']['value'] = $t('Not accessible');
    }
    $requirements['os2dagsorden_importer_acadregroups_url']['severity'] = REQUIREMENT_ERROR;
    $requirements['os2dagsorden_importer_acadregroups_url']['description'] = t('Webservice %variable  is not accessible', array('%variable' => variable_get('os2dagsorden_pws_v_acadregroups_url')));
  }
  else {
    $requirements['os2dagsorden_importer_acadregroups_url']['value'] = $t('Webservice accessible');
    $requirements['os2dagsorden_importer_acadregroups_url']['severity'] = REQUIREMENT_OK;
    $requirements['os2dagsorden_importer_acadregroups_url']['description'] = t('Webservice %variable  is accessible', array('%variable' => variable_get('os2dagsorden_pws_v_acadregroups_url')));
  }
  return $requirements;
}
