<?php

/**
 * @file
 * Code for the os2web_blocks_positioning feature.
 */

include_once 'os2dagsorden_blocks_positioning.features.inc';

/**
 * Gets a GIT version.
 *
 * @return string
 *   Version of git.
 */
function os2dagsorden_blocks_positioning_show_git_version() {
  $gittag = exec('git describe --abbrev=0 --tags');
  $repo_url = exec('git config --get remote.origin.url');
  $info_path = drupal_get_path('profile', 'os2dagsorden') . '/os2dagsorden.info';
  $info = drupal_parse_info_file($info_path);
  $version = (isset($info["version"])) ? $info["version"] : 'no version';
  $gittag = (isset($gittag) || !empty($gittag)) ? $gittag : 'not tagged';
  $output = '<table>';
  $output .= '<tr><td>Version: </td><td>' . $version . '</td></tr>';
  $output .= '<tr><td>Gittag: </td><td>' . $gittag . '</td></tr>';
  $output .= '<tr><td>Github: </td><td><a href="' . $repo_url . '" target="_blank">' . $repo_url . '</a></td></tr>';
  $output .= '</table>';
  return $output;
}

/**
 * Checks if zoom block should be shown.
 *
 * @return bool
 *   TRUE if zoom block should be shown, FALSE otherwise.
 */
function os2dagsorden_blocks_positioning_show_menu_zoom_block() {
  return variable_get('os2dagsorden_frontpage_layout_show_hide_zoom_buttons', FALSE);
}
