<?php

/**
 * @file
 * OS2Dagsorden_simplesaml.
 */

/**
 * Implements hook_menu().
 */
function os2dagsorden_simplesaml_menu() {
  $items = array();

  $items['admin/config/people/simplesaml'] = array(
    'title'            => 'os2dagsorden SimpleSAML',
    'description'      => 'Administer SimpleSAML',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2dagsorden_simplesaml_settings_form'),
    'access arguments' => array('administer syddjurs simplesaml'),
  );

  return $items;
}

/**
 * Form callback for settings.
 */
function os2dagsorden_simplesaml_settings_form($form, &$form_state) {
  $form['os2dagsorden_simplesaml_redirected_ips'] = array(
    '#title'         => t("Redirect IP's to SimpleSAML login"),
    '#type'          => 'textfield',
    '#description'   => t('Comma separated. ex. 192.168.1.1,192.168.2.1,8.8.8.8 - leave empty for all IPs'),
    '#default_value' => variable_get('os2dagsorden_simplesaml_redirected_ips'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save',
  );

  return $form;
}

/**
 * Implements hook_form_validate().
 */
function os2dagsorden_simplesaml_settings_form_validate($form, &$form_state) {
  if (preg_match("/[^0-9.,]/", $form_state['values']['os2dagsorden_simplesaml_redirected_ips'])) {
    form_set_error('os2dagsorden_simplesaml_redirected_ips', 'Invalid format');
  }
}

/**
 * Implements hook_form_submit().
 */
function os2dagsorden_simplesaml_settings_form_submit($form, &$form_state) {
  variable_set('os2dagsorden_simplesaml_redirected_ips', $form_state['values']['os2dagsorden_simplesaml_redirected_ips']);
}

/**
 * Implements hook_boot().
 *
 * If the request comes from one of the IP from variable, then user is
 * redirected to saml login page.
 */
function os2dagsorden_simplesaml_boot() {
  // Do not run this from CLI.
  if (php_sapi_name() != 'cli' && $GLOBALS['user']->uid == 0) {
    $custom_ips = explode(',', variable_get('os2dagsorden_simplesaml_redirected_ips'));
    isset($_SERVER['HTTP_X_FORWARDED_FOR']) ? $remote_ip = $_SERVER['HTTP_X_FORWARDED_FOR'] : $remote_ip = ip_address();

    foreach ($custom_ips as $custom_ip) {
      // If we the client request is from one of the IP's, login using
      // SimpleSAMLphp; otherwise use normal login.
      if ($remote_ip == $custom_ip || empty($custom_ip)) {
        if (!in_array($_GET['q'], array('saml_login', 'user/logout', 'logout'))) {
          require_once DRUPAL_ROOT . '/includes/common.inc';
          require_once DRUPAL_ROOT . '/includes/path.inc';
          drupal_goto('saml_login', array('query' => drupal_get_destination()));
        }
      }
    }
  }
}
